title: Connecting a DC motor to a Crumble
hero_image: images/banner.png
description: connect-motor-crumble description
version: 4
listed: false
copyedit: false
last_tested: "2019-05-24"
steps:
  - title: Connecting a DC motor to a Crumble
